#!/usr/bin/env bash

# Drop any AssumeRole credentials prior to artifact upload, so we can
# upload to our private bucket.
if [[ "${BUILDKITE_STEP_KEY}" =~ "post-command" ]]; then

    echo "--- Before dropping credentials"
    aws sts get-caller-identity

    echo "--- S3 ls"
    set +e
    aws s3 ls s3://grapl-buildkite-artifacts-ecfff1a
    set -e

    echo "--- Unsetting AWS environment variables set by aws-assume-role plugin"
    unset AWS_ACCESS_KEY_ID
    unset AWS_SECRET_ACCESS_KEY
    unset AWS_SESSION_TOKEN

    echo "--- After dropping credentials"
    aws sts get-caller-identity

    echo "--- S3 ls"
    set +e
    aws s3 ls s3://grapl-buildkite-artifacts-ecfff1a
    set -e
fi
